## Загрузка и подготовка данных

In [1]:
import pandas as pd
import numpy as np
from numpy.random import RandomState

import math

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [2]:
data_0 = pd.read_csv('/content/08.geo_data_0.csv')
display(data_0.head(2))
data_1 = pd.read_csv('/content/08.geo_data_1.csv')
display(data_1.head(2))
data_2 = pd.read_csv('/content/08.geo_data_2.csv')
display(data_2.head(2))

id        f0        f1       f2     product
0  txEyH  0.705745 -0.497823  1.22117  105.280062
1  2acmU  1.334711 -0.340164  4.36508   73.037750

id         f0        f1        f2    product
0  kBEdx -15.001348 -8.276000 -0.005876   3.179103
1  62mP7  14.272088 -3.475083  0.999183  26.953261

id        f0        f1        f2    product
0  fwXo0 -1.146987  0.963328 -0.828965  27.758673
1  WJtFt  0.262778  0.269839 -2.530187  56.069697

In [3]:
data_0.info()
data_1.info()
data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   id       100000 non-null  object 
 1   f0       100000 non-null  float64
 2   f1       100000 non-null  float64
 3   f2       100000 non-null  float64
 4   product  100000 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   id       100000 non-null  object 
 1   f0       100000 non-null  float64
 2   f1       100000 non-null  float64
 3   f2       100000 non-null  float64
 4   product  100000 non-null  float64
dtypes: float64(4), object(1)
memory usage: 3.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column   Non-Null 

In [4]:
display(data_0.duplicated().sum())
display(data_1.duplicated().sum())
display(data_2.duplicated().sum())

0

0

0

In [5]:
data_0[data_0.duplicated(subset='id', keep=False)].sort_values('id')

id        f0        f1         f2     product
66136  74z30  1.084962 -0.312358   6.990771  127.643327
64022  74z30  0.741456  0.459229   5.153109  140.771492
51970  A5aEY -0.180335  0.935548  -2.094773   33.020205
3389   A5aEY -0.039949  0.156872   0.209861   89.249364
69163  AGS9W -0.933795  0.116194  -3.655896   19.230453
42529  AGS9W  1.454747 -0.479651   0.683380  126.370504
931    HZww2  0.755284  0.368511   1.863211   30.681774
7530   HZww2  1.061194 -0.373969  10.430210  158.828695
63593  QcMuo  0.635635 -0.473422   0.862670   64.578675
1949   QcMuo  0.506563 -0.323775  -2.215583   75.496502
75715  Tdehs  0.112079  0.430296   3.218993   60.964018
21426  Tdehs  0.829407  0.298807  -0.049563   96.035308
92341  TtcGQ  0.110711  1.022689   0.911381  101.318008
60140  TtcGQ  0.569276 -0.104876   6.440215   85.350186
89582  bsk9y  0.398908 -0.400253  10.122376  163.433078
97785  bsk9y  0.378429  0.005837   0.160827  160.637302
41724  bxg6G -0.823752  0.546319   3.630479   93.007798
1364   bxg6G  0.411645  0.856830  -3.653440   73.604260
16633  fiKDv  0.157341  1.028359   5.585586   95.817889
90815  fiKDv  0.049883  0.841313   6.394613  137.346586

In [6]:
data_0.drop_duplicates(['id'], inplace=True)
print(data_0)

          id        f0        f1        f2     product
0      txEyH  0.705745 -0.497823  1.221170  105.280062
1      2acmU  1.334711 -0.340164  4.365080   73.037750
2      409Wp  1.022732  0.151990  1.419926   85.265647
3      iJLyR -0.032172  0.139033  2.978566  168.620776
4      Xdl7t  1.988431  0.155413  4.751769  154.036647
...      ...       ...       ...       ...         ...
99995  DLsed  0.971957  0.370953  6.075346  110.744026
99996  QKivN  1.392429 -0.382606  1.273912  122.346843
99997  3rnvd  1.029585  0.018787 -1.348308   64.375443
99998  7kl59  0.998163 -0.528582  1.583869   74.040764
99999  1CWhH  1.764754 -0.266417  5.722849  149.633246

[99990 rows x 5 columns]


In [7]:
data_1[data_1.duplicated(subset='id', keep=False)].sort_values('id')

id         f0         f1        f2     product
5849   5ltQ6  -3.435401 -12.296043  1.999796   57.085625
84461  5ltQ6  18.213839   2.191999  3.993869  107.813044
1305   LHZR0  11.170835  -1.945066  3.002872   80.859783
41906  LHZR0  -8.989672  -4.286607  2.009139   57.085625
2721   bfPNe  -9.494442  -5.463692  4.006042  110.992147
82178  bfPNe  -6.202799  -4.820045  2.995107   84.038886
47591  wt4Uk  -9.091098  -8.109279 -0.002314    3.179103
82873  wt4Uk  10.259972  -9.376355  4.994297  134.766305

In [8]:
data_1.drop_duplicates(['id'], inplace=True)

In [9]:
data_2[data_2.duplicated(subset='id', keep=False)].sort_values('id')

id        f0        f1        f2     product
45404  KUPhW  0.231846 -1.698941  4.990775   11.716299
55967  KUPhW  1.211150  3.176408  5.543540  132.831802
11449  VF7Jo  2.122656 -0.858275  5.746001  181.716817
49564  VF7Jo -0.883115  0.560537  0.723601  136.233420
44378  Vcm5J -1.229484 -2.439204  1.222909  137.968290
95090  Vcm5J  2.587702  1.986875  2.482245   92.327572
28039  xCHr8  1.633027  0.368135 -2.378367    6.120525
43233  xCHr8 -0.847066  2.101796  5.597130  184.388641

In [10]:
data_2.drop_duplicates(['id'], inplace=True)

In [11]:
print(data_0)

          id        f0        f1        f2     product
0      txEyH  0.705745 -0.497823  1.221170  105.280062
1      2acmU  1.334711 -0.340164  4.365080   73.037750
2      409Wp  1.022732  0.151990  1.419926   85.265647
3      iJLyR -0.032172  0.139033  2.978566  168.620776
4      Xdl7t  1.988431  0.155413  4.751769  154.036647
...      ...       ...       ...       ...         ...
99995  DLsed  0.971957  0.370953  6.075346  110.744026
99996  QKivN  1.392429 -0.382606  1.273912  122.346843
99997  3rnvd  1.029585  0.018787 -1.348308   64.375443
99998  7kl59  0.998163 -0.528582  1.583869   74.040764
99999  1CWhH  1.764754 -0.266417  5.722849  149.633246

[99990 rows x 5 columns]


**В итоге:**

1. Выгрузила данные, посмотрела есть ли пропуски.
2. Проверила дубликаты, тип данных.
3. Удалила дубликаты. Их немного, похоже это были предыдущие замеры.

## Обучение и проверка модели

<u>Обучение 1 модели</u>

In [12]:
train_0, valid_0 = train_test_split(data_0, test_size = 0.25, random_state=12345)
features_train_0 = train_0.drop(['id','product'], axis=1)
target_train_0 = train_0['product']
features_valid_0 = valid_0.drop(['id','product'], axis=1)
target_valid_0 = valid_0['product']

ml0= [features_train_0, target_train_0, features_valid_0, target_valid_0]
for i in ml0:
  print(i.shape)

(74992, 3)
(74992,)
(24998, 3)
(24998,)


In [13]:
scaler_0 = StandardScaler()

scaler_0.fit(features_train_0)
features_train_0 = scaler_0.transform(features_train_0)
features_valid_0 = scaler_0.transform(features_valid_0)
print(features_train_0)

[[ 0.77628656 -1.25512042 -0.06752751]
 [-1.58037754 -0.17670418 -1.28179535]
 [-0.64631932  0.13696619 -0.50542993]
 ...
 [ 0.41706672 -1.29709735 -0.19483864]
 [-0.62852588  1.5548936  -1.23942191]
 [ 0.93757021 -1.5024128  -1.62623282]]


In [14]:
model_0 = LinearRegression()
model_0.fit(features_train_0, target_train_0)
predictions_0 = model_0.predict(features_valid_0)
rmse_0 = mean_squared_error(target_valid_0, predictions_0) ** 0.5
pred_mean_0 = predictions_0.mean()

<u>Обучение 2 модели</u>

In [15]:
train_1, valid_1 = train_test_split(data_1, test_size = 0.25, random_state=12345)
features_train_1 = train_1.drop(['id','product'], axis=1)
target_train_1 = train_1['product']
features_valid_1 = valid_1.drop(['id','product'], axis=1)
target_valid_1 = valid_1['product']

ml1= [features_train_1, target_train_1, features_valid_1, target_valid_1]
for i in ml1:
  print(i.shape)

(74997, 3)
(74997,)
(24999, 3)
(24999,)


In [16]:
scaler_1 = StandardScaler()

scaler_1.fit(features_train_1)
features_train_1 = scaler_1.transform(features_train_1)
features_valid_1 = scaler_1.transform(features_valid_1)
print(features_train_1)

[[ 1.96996853  1.83743507  0.29739707]
 [-0.81462967  1.7292981   0.30341265]
 [-1.13794929  0.73432669  1.47639755]
 ...
 [ 1.04569417 -0.64786067  1.47546075]
 [-1.10014704 -1.10165172  0.3003845 ]
 [-0.14693389  0.18166275 -1.45971777]]


In [17]:
model_1 = LinearRegression()
model_1.fit(features_train_1, target_train_1)
predictions_1 = model_1.predict(features_valid_1)
rmse_1 = mean_squared_error(target_valid_1, predictions_1) ** 0.5
pred_mean_1 = predictions_1.mean()

<u>Обучение 3 модели</u>

In [18]:
train_2, valid_2 = train_test_split(data_2, test_size = 0.25, random_state=12345)
features_train_2 = train_2.drop(['id','product'], axis=1)
target_train_2 = train_2['product']
features_valid_2 = valid_2.drop(['id','product'], axis=1)
target_valid_2 = valid_2['product']

ml2= [features_train_2, target_train_2, features_valid_2, target_valid_2]
for i in ml2:
  print(i.shape)

(74997, 3)
(74997,)
(24999, 3)
(24999,)


In [19]:
scaler_2 = StandardScaler()

scaler_2.fit(features_train_2)
features_train_2 = scaler_2.transform(features_train_2)
features_valid_2 = scaler_2.transform(features_valid_2)
print(features_train_2)

[[-0.89149166 -0.4048719  -1.22610371]
 [-0.56695458 -0.0997629   1.10057015]
 [ 1.63849399 -0.03168196  0.80304173]
 ...
 [ 0.36537996  0.79582506  0.6648428 ]
 [-0.9165434   0.85163998  1.63599776]
 [ 0.00843773  0.02691125  0.63098462]]


In [20]:
model_2 = LinearRegression()
model_2.fit(features_train_2, target_train_2)
predictions_2 = model_2.predict(features_valid_2)
rmse_2 = mean_squared_error(target_valid_2, predictions_2) ** 0.5
pred_mean_2 = predictions_2.mean()


Смотрим предсказания запаса и ошибки:

In [21]:
reserve = pd.DataFrame(index=['Предположит.ср.запас сырья','RMSE'], columns=['1 регион','2 регион','3 регион'])
reserve['1 регион'] = pred_mean_0, rmse_0
reserve['2 регион'] = pred_mean_1, rmse_1
reserve['3 регион'] = pred_mean_2, rmse_2
display(reserve)

1 регион   2 регион   3 регион
Предположит.ср.запас сырья  92.789156  69.178320  94.865725
RMSE                        37.853527   0.892059  40.075851

**В итоге:**
1. Произвела стандартизацию даннных с помощью `StandardScaler()`
2. Самый большой запас сырья у нас в третьем регионе. Но и доля ошибки тут высокая.
3. Учитывая долю ошибки, лучше всех выглядит 2 регион.

## Подготовка к расчёту прибыли

Имею следующие исходные данные

In [22]:
budget = 10000000000
income_borehole = 450
probability_losses = 0.025
wells = 500
super_wells = 200

Бюджет одной скважины без убытков - это бюджет разделить на количество скважин и итог разделить на стоимость барреля

In [23]:
budg_one_borehole=(budget/200)/income_borehole
print('Бюджет на разработку безубыточной скважины:', math.ceil(budg_one_borehole),'руб.')

Бюджет на разработку безубыточной скважины: 111112 руб.


Считаю запас нефти в регионах

In [24]:
product_0 = data_0['product'].mean()
product_1 = data_1['product'].mean()
product_2 = data_2['product'].mean()

Помещаю данные в таблицу для удобства чтения

In [25]:
reserve = pd.DataFrame(index=['Cредний запас сырья в регионе'], columns=['1 регион','2 регион','3 регион'])
reserve['1 регион'] = product_0
reserve['2 регион'] = product_1
reserve['3 регион'] = product_2
display(reserve)

1 регион   2 регион   3 регион
Cредний запас сырья в регионе  92.499684  68.823916  94.998342

Ни в одном регионе нет достаточного запаса для безубыточной разработки:
нужно смотреть по скважинам.

## Расчёт прибыли и рисков

Нахожу прибыль от 200 лучших сважин по каждому региону:
1. пишу фукнцию для подсчета прибыли из 200 лучших сважин;
2. сортирую ответы до 200, умножаю на 1000 повторений, считаю сумму;
Подставляем данные 1 региона;
3. ответы и предсказания записываю в `Series`.

In [26]:
def revenue(target, probabilites, count):
    probs_sorted = probabilites.sort_values(ascending=False)
    selected = target[probs_sorted.index][: count]
    return (income_borehole * 1000 * selected.sum())-budget


target_valid_0 = pd.Series(target_valid_0).reset_index(drop=True)
predictions_0 = pd.Series(predictions_0).reset_index(drop=True)

target_valid_1 = pd.Series(target_valid_1).reset_index(drop=True)
predictions_1 = pd.Series(predictions_1).reset_index(drop=True)

target_valid_2 = pd.Series(target_valid_2).reset_index(drop=True)
predictions_2 = pd.Series(predictions_2).reset_index(drop=True)


Нахожу доверительный интервал и возможную долю убытков


In [27]:
target = [target_valid_0, target_valid_1, target_valid_2]
predictions = [predictions_0, predictions_1, predictions_2]
regions = ['Первый регион', 'Второй регион', 'Третий регион']

state = np.random.RandomState(12345)

for m in range(len(target)):
    values = []
    for i in range(1000):
        target_subsample = target[m].sample(n=wells, replace=True, random_state=state)
        predictions_subsample = predictions[m].loc[target_subsample.index]
        values.append(revenue(target_subsample.reset_index(drop=True), predictions_subsample.reset_index(drop=True), super_wells))

    values = pd.Series(values)
    lower = values.quantile(.025)
    upper = values.quantile(.975)

    mean = values.mean()

    loser_probs = sum(values < 0) / values.count() * 100

    print(regions[m])
    print("Средняя прибыль:", mean)
    print("95%-доверительный интервал:", lower, "-", upper)
    print("Вероятность убытков:", loser_probs, "%")

Первый регион
Средняя прибыль: 380613470.0175977
95%-доверительный интервал: -142942739.74041605 - 890976833.8485551
Вероятность убытков: 7.7 %
Второй регион
Средняя прибыль: 479159869.981588
95%-доверительный интервал: 73849212.0224793 - 917953817.7221825
Вероятность убытков: 0.6 %
Третий регион
Средняя прибыль: 315441916.0234899
95%-доверительный интервал: -216265050.0341763 - 811060708.2365634
Вероятность убытков: 12.4 %


## Вывод

###Второй регион самый подходящий для разработки:
1. У него самая маленькая вероятность убытков.
2. Высокая самая средняя прибыль.